### ISSUE TITLE
Allow vectors in and out of rate matrix expressions

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#103]
# Story

As a pandemic modeller, I want to be able to get the speed benefits from TMB for models with structure, so that I can try out more models.

Note: Starting with vaxination as the test case.

# Tasks

- [x] Symbolic manipulation of matrices and vectors
- [x] Make it possible to assign scalar expressions to multiple rates
- [x] allow character and struc 'formulas'
- [x] express foi as model structure
- [x] Make it possible to assign vector expressions to multiple rates
