### ISSUE TITLE
Function for converting flex model into TMB AD function

### ISSUE THREAD

**Issue by stevencarlislewalker** [mac-theobio/McMasterPandemic#91]
# Tasks

- [x] Decide on design
- [x] Add functionality to the package on TMB branch
- [x] Refactor tests appropriately 

# Design Notes

Tempted to convert flex models to R6 objects, and then using methods rather than pipes.  In this case, the AD function could be wrapped up in an R6 method. But would this provide value beyond making Python people feel better?
